package main

import (
	"context"
	"errors"
	"fmt"

	"github.com/jaxxstorm/dnsscale/providers"
	"go.uber.org/zap"
)

// sweep reconciles the whole zone against the desired state in one pass: it
// writes any static records that are missing or wrong, and reclaims records
// whose owner no longer exists.
//
// The per-node reconcile path handles the common case of a node appearing or
// changing. This exists because that path cannot see the whole picture: it
// never learns about records left behind by a previous run (whether from a
// crash, or from the period when the delete path was broken), or about static
// records dropped from the configuration.
func (r *DNSReconciler) sweep(ctx context.Context) error {
	existing, err := r.dnsProvider.ListRecords(ctx, r.domain)
	if err != nil {
		return fmt.Errorf("list records: %w", err)
	}

	desired, owners := r.desiredState()

	var failures []error
	if err := r.applyMissing(ctx, desired, existing); err != nil {
		failures = append(failures, err)
	}
	if err := r.reclaimOrphans(ctx, desired, owners, existing); err != nil {
		failures = append(failures, err)
	}
	return errors.Join(failures...)
}

// recordKey identifies a record for comparison purposes. Names are normalized
// so a name generated by dnsscale compares equal to the same name as the
// provider spells it.
type recordKey struct {
	name       string
	recordType string
}

func keyFor(record providers.DNSRecord) recordKey {
	return recordKey{name: normalizeName(record.Name), recordType: record.Type}
}

// desiredState returns the records dnsscale wants to exist, keyed for lookup,
// along with the set of owners that are currently legitimate.
func (r *DNSReconciler) desiredState() (map[recordKey]providers.DNSRecord, map[string]bool) {
	desired := make(map[recordKey]providers.DNSRecord)
	owners := map[string]bool{ownerStatic: true}

	r.cacheMutex.RLock()
	nodes := make([]TailscaleNode, 0, len(r.nodeCache))
	for _, node := range r.nodeCache {
		nodes = append(nodes, node)
	}
	r.cacheMutex.RUnlock()

	for _, node := range nodes {
		if !r.shouldManageNode(node) {
			continue
		}
		owners[node.ID] = true
		for _, record := range r.recordsForNode(node) {
			desired[keyFor(record)] = record
		}
	}

	for _, record := range r.staticRecords() {
		desired[keyFor(record)] = record
	}

	return desired, owners
}

// applyMissing writes the static records that are absent or hold the wrong
// value. Node records are left to the per-node reconcile path, which already
// runs whenever a node changes.
func (r *DNSReconciler) applyMissing(ctx context.Context, desired map[recordKey]providers.DNSRecord, existing []providers.DNSRecord) error {
	if len(r.static) == 0 {
		return nil
	}

	current := make(map[recordKey]providers.DNSRecord, len(existing))
	for _, record := range existing {
		current[keyFor(record)] = record
	}

	var failures []error
	for _, record := range r.staticRecords() {
		if have, ok := current[keyFor(record)]; ok && have.Value == record.Value && have.TTL == record.TTL {
			continue
		}

		if err := r.dnsProvider.UpdateRecord(ctx, r.domain, record); err != nil {
			r.logger.Error("Failed to write static record",
				zap.String("record_name", record.Name),
				zap.String("record_type", record.Type),
				zap.Error(err))
			failures = append(failures, fmt.Errorf("update %s %s: %w", record.Type, record.Name, err))
			continue
		}

		r.logger.Info("Updated static DNS record",
			zap.String("record_name", record.Name),
			zap.String("record_type", record.Type),
			zap.String("record_value", record.Value))
	}

	return errors.Join(failures...)
}

// reclaimOrphans deletes records dnsscale owns that it no longer wants.
//
// Only names carrying a dnsscale ownership marker are ever considered, so
// records created by anything else in the zone are never touched.
func (r *DNSReconciler) reclaimOrphans(ctx context.Context, desired map[recordKey]providers.DNSRecord, owners map[string]bool, existing []providers.DNSRecord) error {
	// Work out which names dnsscale owns, and whether each is still wanted.
	orphaned := make(map[string]string) // normalized name -> owner
	for _, record := range existing {
		if record.Type != "TXT" {
			continue
		}
		owner, ok := ownerFromValue(record.Value)
		if !ok {
			continue
		}

		name := normalizeName(record.Name)

		// A name is orphaned when its owner is gone (node removed from the
		// tailnet, or no longer matching the tag filter), or when the owner still
		// exists but no longer claims this name (an alias removed from config).
		if !owners[owner] {
			orphaned[name] = owner
			continue
		}
		if _, wanted := desired[recordKey{name: name, recordType: "TXT"}]; !wanted {
			orphaned[name] = owner
		}
	}

	if len(orphaned) == 0 {
		return nil
	}

	var failures []error
	for _, record := range existing {
		name := normalizeName(record.Name)
		owner, isOrphan := orphaned[name]
		if !isOrphan {
			continue
		}

		if err := r.dnsProvider.DeleteRecord(ctx, r.domain, record); err != nil {
			// A concurrent per-node delete may have removed this already, which
			// is not a problem worth failing the sweep over.
			r.logger.Warn("Failed to reclaim orphaned DNS record",
				zap.String("record_name", record.Name),
				zap.String("record_type", record.Type),
				zap.String("owner", owner),
				zap.Error(err))
			failures = append(failures, fmt.Errorf("delete %s %s: %w", record.Type, record.Name, err))
			continue
		}

		r.logger.Info("Reclaimed orphaned DNS record",
			zap.String("record_name", record.Name),
			zap.String("record_type", record.Type),
			zap.String("owner", owner))
	}

	return errors.Join(failures...)
}
