FROM docker.io/library/golang:1.24-alpine as builder
RUN apk add --no-cache git
WORKDIR /go/src
RUN git clone https://github.com/jmeekhof/dnsscale.git
WORKDIR /go/src/dnsscale
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download
RUN --mount=type=cache,target=/go/pkg/mod \
    GOARCH=$TARGETARCH go build

FROM alpine:3.22
COPY --from=builder /go/src/dnsscale/dnsscale /usr/local/bin
ENTRYPOINT ["/usr/local/bin/dnsscale"]
